events {}

http {
    # Увеличиваем максимальный размер тела запроса
    client_max_body_size 20M;  # Разрешаем загрузку файлов до 20 МБ
    
    upstream backend {
        server back:8080;  # Имя сервиса из docker-compose
    }

    server {
        listen 80;
        
        location / {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            # Увеличиваем таймауты для больших файлов
            proxy_connect_timeout 60s;
            proxy_read_timeout 300s;  # Увеличиваем для загрузки больших файлов
            proxy_send_timeout 300s;
            
            # Увеличиваем буферы для больших запросов
            proxy_buffer_size 128k;
            proxy_buffers 4 256k;
            proxy_busy_buffers_size 256k;
            
            # Для CORS preflight - только OPTIONS
            if ($request_method = 'OPTIONS') {
                add_header 'Access-Control-Allow-Origin' 'http://localhost:5173';
                add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, PATCH, DELETE, OPTIONS';
                add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization';
                add_header 'Access-Control-Max-Age' 1728000;
                add_header 'Content-Type' 'text/plain; charset=utf-8';
                add_header 'Content-Length' 0;
                return 204;
            }
        }
    }
}