CREATE TABLE IF NOT EXISTS "agents"
(
    "id"           INTEGER      NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "user_id"      INTEGER      NOT NULL,
    "company_name" VARCHAR(255) NOT NULL,
    "avatar"       VARCHAR(255),
    PRIMARY KEY ("id")
);
