CREATE TABLE IF NOT EXISTS "apartment" (
                                           "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                                           "status" VARCHAR(255) NOT NULL,
                                           "address" VARCHAR(255) NOT NULL,
                                           "house_date" SMALLINT NOT NULL,
                                           "floor" SMALLINT NOT NULL,
                                           "square" SMALLINT NOT NULL,
                                           "room_number" SMALLINT NOT NULL,
                                           "price" INTEGER NOT NULL,
                                           "agent_id" INTEGER NOT NULL,
                                           "photo" VARCHAR(255) NOT NULL,
                                           "description" VARCHAR(255) NOT NULL,
                                           "district" VARCHAR(255) NOT NULL,
                                           "apart_type" VARCHAR(255) NOT NULL,
                                           "geotag" VARCHAR(255),
                                           PRIMARY KEY("id")
);
