CREATE TABLE IF NOT EXISTS "feedbacks" (
    "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "apart_id" INTEGER NOT NULL,
    "user_id" INTEGER NOT NULL,
    "feedback_text" VARCHAR(255) NOT NULL,
    "feedback_photo" VARCHAR(255),
    PRIMARY KEY("id")
);
