CREATE TABLE IF NOT EXISTS "apartment" (
                                           "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                                           "status" SMALLINT NOT NULL,
    "address" VARCHAR(255) NOT NULL,
    "house_date" SMALLINT NOT NULL,
    "floor" SMALLINT NOT NULL,
    "square" SMALLINT NOT NULL,
    "room_number" SMALLINT NOT NULL,
    "price" INTEGER NOT NULL,
    "agent_id" INTEGER NOT NULL,
    "photo" TEXT NOT NULL,
    "description" VARCHAR(255) NOT NULL,
    "district" VARCHAR(255) NOT NULL,
    PRIMARY KEY("id")
    );
CREATE TABLE IF NOT EXISTS "feedbacks" (
                                               "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                                               "apart_id" INTEGER NOT NULL,
                                               "user_id" INTEGER NOT NULL,
                                               "feedback_text" VARCHAR(255) NOT NULL,
        "feedback_photo" TEXT NOT NULL,
    PRIMARY KEY("id")
    );
CREATE TABLE IF NOT EXISTS "feedbacks_on_agent" (
                                                   "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                                                   "agent_id" INTEGER NOT NULL,
                                                   "user_id" INTEGER NOT NULL,
                                                   "text" VARCHAR(255) NOT NULL,
    PRIMARY KEY("id")
    );
CREATE TABLE IF NOT EXISTS "agents"
(
    "id"           INTEGER      NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "user_id"      INTEGER      NOT NULL,
    "company_name" VARCHAR(255) NOT NULL,
    "avatar"       VARCHAR(255),
    PRIMARY KEY ("id")
    );
CREATE TABLE IF NOT EXISTS "users"
(
    "id"       INTEGER      NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "email"    VARCHAR(255) NOT NULL,
    "password" VARCHAR(255) NOT NULL,
    "name"     VARCHAR(255) NOT NULL,
    "role"     VARCHAR(255) NOT NULL,
    PRIMARY KEY ("id")
    );
ALTER TABLE "apartment"
    ADD FOREIGN KEY("agent_id") REFERENCES "agents"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "feedbacks"
    ADD FOREIGN KEY ("apart_id") REFERENCES "apartment" ("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "feedbacks"
    ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "feedbacks_on_agent"
    ADD FOREIGN KEY ("agent_id") REFERENCES "agents" ("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "feedbacks_on_agent"
    ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "agents"
    ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;